version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    restart: unless-stopped

  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    restart: unless-stopped
